### ISSUE TITLE
Bring back .parse

### ISSUE THREAD

**Issue by icco** [waiting-for-dev/front_matter_parser#1]
I would love if I could call parse on a string, which doesn't seem to work with the new rewrite. I tried the following three, and all throw exceptions.

```
FrontMatterParser.parse(body)
```

```
prsr = FrontMatterParser::Parser.new(:slim)
fmp = prsr.parse(body)
```

```
FrontMatterParser::Parser.parse(body)
```

**Comment by icco** [comment]
Thoughts @waiting-for-dev?

**Comment by waiting-for-dev** [comment]
Hi @icco ,

I now see that I made a mistake in the README. The method to parse a string has been renamed to `call` (as instance method):

```ruby
prsr = FrontMatterParser::Parser.new(:slim)
fmp = prsr.call(body)
```

This has been a major rewrite of the library. From now on you can expect the API to be more stable.

The README is now fixed.

**Comment by icco** [comment]
That works, thanks!
