### ISSUE TITLE
Bring back support for un-commented frontmatter.

### ISSUE THREAD

**Issue by icco** [waiting-for-dev/front_matter_parser#2]
My frontmatter follows the jekyll spec, and looks like https://raw.githubusercontent.com/icco/blog-backup/83b109a828564db39b995b59ca852ff9e61d0412/_posts/2017-03-16-644.md. With 0.1.0 you seem to have dropped support of this frontmatter style.

**Comment by waiting-for-dev** [comment]
Hi @icco , you can still parse that kind of front matters with the `:md` syntax. Is it clear how?

**Comment by icco** [comment]
Perfect, thanks!
